import type { Metadata } from "next";
import { Fill, LegalPage } from "@/components/legal-page";
import { COMPANY } from "@/lib/company";

export const metadata: Metadata = {
  title: "Acceptable Use Policy",
  description:
    "What Arka will and will not generate, and how to report something that should not exist.",
};

const UPDATED = "25 September 2026";

/**
 * The policy behind the enforcement.
 *
 * `src/lib/moderation.ts` refuses a narrow set of requests and the admin can
 * take anything down. Neither means much without a published statement of what
 * the rules are and how to invoke them — and the IT Rules 2021 require the
 * grievance route to be reachable and answered on a clock.
 */
export default function AcceptableUsePage() {
  return (
    <LegalPage title="Acceptable Use Policy" updated={UPDATED}>
      <p>
        Arka generates video from a line of text. That makes it useful, and it
        makes it possible to misuse. This page says plainly what we will not
        generate and what happens when someone tries.
      </p>

      <h2>What Arka will not generate</h2>
      <ul>
        <li>
          <strong>The likeness of a real person.</strong> Public figure or
          private individual, living or dead. Describe a character — age, dress,
          bearing — and the model will invent a face. Do not ask it for someone
          else&rsquo;s.
        </li>
        <li>
          <strong>Religious figures depicted degradingly.</strong> Devotional and
          mythological work is the whole point of this product and is welcome.
          Sexualised, mocking or desecratory depictions of any faith&rsquo;s
          figures are not, and are refused at submission.
        </li>
        <li>
          <strong>Anything sexualising a minor.</strong> No exceptions, no
          artistic-intent argument, and accounts are terminated rather than
          warned.
        </li>
        <li>
          <strong>Incitement against a group.</strong> Depictions of violence
          targeting a religion, caste or community.
        </li>
        <li>
          <strong>Deception.</strong> Passing generated footage off as a
          recording of something that happened — news events, evidence, or a
          person&rsquo;s statement.
        </li>
      </ul>

      <h2>Everything Arka makes is AI-generated</h2>
      <p>
        Every video is watermarked in its file metadata as AI-generated. Leave
        that intact, and label the output as synthetic when you publish it
        somewhere it could be mistaken for a recording. This is increasingly a
        legal requirement as well as a courtesy.
      </p>

      <h2>Who owns the output</h2>
      <p>
        You do. You keep the rights to the videos you generate and may use them
        commercially, subject to this policy. We claim no ownership over your
        prompts or your renders, and we do not train models on them.
      </p>
      <p>
        We generate through third-party models trained on large public datasets.
        We cannot guarantee an output is free of resemblance to existing work, so
        for anything high-stakes, check before you publish.
      </p>

      <h2>How this is enforced</h2>
      <ul>
        <li>Some requests are refused automatically when you submit them.</li>
        <li>
          We can remove any generated content from our systems and suspend the
          account that made it.
        </li>
        <li>
          Removals are recorded in an audit log, so an enforcement decision can
          always be reviewed.
        </li>
        <li>
          Credits spent on content removed for a policy breach are not refunded.
        </li>
      </ul>

      <h2>Reporting something</h2>
      <p>
        If you have found content generated by Arka that breaks this policy, or
        that uses your likeness or your work,{" "}
        <a href="/grievance">report it here</a> — you do not need an account,
        and you get a reference number and a deadline straight away. You can
        also write to <Fill value={COMPANY.email.abuse}>abuse email address</Fill>.
      </p>

      <h2>Grievance Officer</h2>
      <p>
        In line with the Information Technology (Intermediary Guidelines and
        Digital Media Ethics Code) Rules, 2021 and the Digital Personal Data
        Protection Act, 2023, our Grievance Officer is:
      </p>
      <ul>
        <li>
          <strong>Name:</strong>{" "}
          <Fill value={COMPANY.grievanceOfficer.name}>officer name</Fill>
        </li>
        <li>
          <strong>Email:</strong>{" "}
          <Fill value={COMPANY.grievanceOfficer.email}>officer email</Fill>
        </li>
        <li>
          <strong>Address:</strong>{" "}
          <Fill value={COMPANY.registeredAddress.street}>street address</Fill>,{" "}
          <Fill value={COMPANY.registeredAddress.cityStatePin}>
            city, state and PIN
          </Fill>
        </li>
        <li>
          <strong>Response time:</strong>{" "}
          <Fill value={COMPANY.grievanceOfficer.responseSla}>
            acknowledgement and resolution timeline
          </Fill>
        </li>
      </ul>
      <p>
        Complaints are acknowledged and resolved within the timeline above. If
        you are not satisfied with the outcome, the order it was made under is
        available on request from{" "}
        <Fill value={COMPANY.email.legal}>legal email address</Fill>.
      </p>
    </LegalPage>
  );
}
